# Config file for automatic testing at travis-ci.org

language: python
# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy3"
  - "pypy"

install:
  - pip install -U -r dev-requirements.txt

#before_script:
#  - flake8 .

script: PATH=./tests/ffmpeg:$PATH PYTHONPATH=. py.test tests  # is setting PYTHONPATH the right thing to do?
