name: ci

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: x64
      - run: |
          pip install pre-commit
          pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
          - "pypy3.9"
          - "pypy3.10"
          - "pypy3.11"
    name: test ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - uses: astral-sh/setup-uv@v6
      - run: |
          uv sync
          uv run pytest --cov=ffmpy --cov-report xml
          uv sync --extra psutil
          uv run pytest --cov=ffmpy --cov-report xml --cov-append
      - uses: codecov/codecov-action@v4
        if: matrix.python-version == 3.12
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

  publish:
    runs-on: ubuntu-latest
    name: publish
    if: github.ref_type == 'tag'
    needs:
      - lint
      - test
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: x64
      - uses: astral-sh/setup-uv@v6
      - run: uv build
      - uses: pypa/gh-action-pypi-publish@release/v1
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
